name: real_estate_agency
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  bloc: ^9.2.0
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true
